# Generated by Django 3.0.4 on 2020-03-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_of_receipt',
            field=models.DateTimeField(verbose_name='date of receipt'),
        ),
    ]
